controller_list:
  #  - name: arm_controller
  - name: /execute_trajectory/goal

    #  - name: lwr/lwr_joint_trajectory_action_controller
    type: FollowJointTrajectory
    default: true
    action_ns: /
    joints:
      - lwr_arm_0_joint
      - lwr_arm_1_joint
      - lwr_arm_2_joint
      - lwr_arm_3_joint
      - lwr_arm_4_joint
      - lwr_arm_5_joint
      - lwr_arm_6_joint
  #
  #  - name: gripper_adapter_server
  - name: wsg_50_gripper_action_server
    type: GripperCommand
    default: true
    action_ns: /
    joints:
      - wsg_50_gripper_base_joint_gripper_left
      - wsg_50_gripper_base_joint_gripper_right
