controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - lwr_arm_0_joint
      - lwr_arm_1_joint
      - lwr_arm_2_joint
      - lwr_arm_3_joint
      - lwr_arm_4_joint
      - lwr_arm_5_joint
      - lwr_arm_6_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - wsg_50_gripper_base_joint_gripper_left
      - wsg_50_gripper_base_joint_gripper_right
initial:  # Define initial robot poses.
  - group: arm
    pose: candle
  - group: gripper
    pose: open