# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: candle
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - lwr_arm_0_joint
    - lwr_arm_1_joint
    - lwr_arm_2_joint
    - lwr_arm_3_joint
    - lwr_arm_4_joint
    - lwr_arm_5_joint
    - lwr_arm_6_joint
    - wsg_50_gripper_base_joint_gripper_left
    - wsg_50_gripper_base_joint_gripper_right
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: lwr
    action_ns: "follow_joint_trajectory"
    default: True
    type: FollowJointTrajectory
    joints:
      - lwr_arm_0_joint
      - lwr_arm_1_joint
      - lwr_arm_2_joint
      - lwr_arm_3_joint
      - lwr_arm_4_joint
      - lwr_arm_5_joint
      - lwr_arm_6_joint
  - name: wsg_50_gripper_action_server
    action_ns: ""
    default: True
    type: GripperCommand
# todo: test if this works in real robot
#    allowed_execution_duration_scaling: 5.0
#    allowed_goal_duration_margin: 0.5
    joints:
      - wsg_50_gripper_base_joint_gripper_left
      - wsg_50_gripper_base_joint_gripper_right
