<?xml version="1.0"?>
<robot name="green_table" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--
       The wooden lab/experiment tables in lab room F328
       are 180x85 cm2 and height 79cm,
       Leg diameter is set to 6cm.
  -->

  <xacro:property name="table_height" value="0.79" />
  <xacro:property name="table_width" value="1.80" />
  <xacro:property name="table_depth" value="0.85" />
  <xacro:property name="leg_radius" value="0.03" />
  <xacro:property name="table_x" value="0.0" />
  <xacro:property name="table_y" value="0.0" />
  <xacro:property name="table_z" value="0.0" />

  <xacro:property name="table_top_thickness" value="0.04"/>

  <link name="table_plate">
    <inertial>
      <mass value="8.0" />
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <inertia ixx="1" ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <geometry>
        <box size="${table_width} ${table_depth} ${table_top_thickness}" />
      </geometry>
      <material name="Grey" />
    </visual>
    <collision>
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <geometry>
        <box size="${table_width} ${table_depth} ${table_top_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="table_plate">
    <!-- <material>Gazebo/Wood</material>  -->
    <material>handle/KotoWood</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>false</selfCollide>
  </gazebo>

  <xacro:macro name="leg" params="name *origin">

    <link name="${name}">
      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 ${table_height/2 - table_top_thickness/2}" />
        <inertia ixx="0.1" ixy="0"  ixz="0" iyy="0.1" iyz="0" izz="0.01" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${table_height/2 - table_top_thickness/2}" />
        <geometry>
          <box size="${2*leg_radius} ${2*leg_radius} ${table_height-table_top_thickness}" />
        </geometry>
        <material name="Grey" />
      </visual>
      <collision>
        <origin xyz="0 0 ${table_height/2-table_top_thickness/2}" />
        <geometry>
          <box size="${2*leg_radius} ${2*leg_radius} ${table_height-table_top_thickness}" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="${name}">
      <material>handle/KotoWood</material>
      <mu1>1000.0</mu1>
      <mu2>1000.0</mu2>
      <kp>10000000.0</kp>
      <kd>1.0</kd>
      <selfCollide>false</selfCollide>
    </gazebo>

    <joint name="${name}_joint" type="fixed" >
      <parent link="table_plate" />
      <xacro:insert_block name="origin" />
      <child link="${name}" />
    </joint>

  </xacro:macro>

  <xacro:leg name="leg1">
    <origin xyz="${-0.5*table_width+leg_radius} ${-0.5*table_depth+leg_radius} 0" rpy="0 0 0" />
  </xacro:leg>

  <xacro:leg name="leg2">
    <origin xyz="${-0.5*table_width+leg_radius} ${+0.5*table_depth-leg_radius} 0" rpy="0 0 0" />
  </xacro:leg>

  <xacro:leg name="leg3">
    <origin xyz="${+0.5*table_width-leg_radius} ${-0.5*table_depth+leg_radius} 0" rpy="0 0 0" />
  </xacro:leg>

  <xacro:leg name="leg4">
    <origin xyz="${+0.5*table_width-leg_radius} ${+0.5*table_depth-leg_radius} 0" rpy="0 0 0" />
  </xacro:leg>

  <link name="styrofoam_plate">
    <inertial>
      <mass value="0.02" />
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <inertia ixx="1" ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <geometry>
        <box size="1.0 0.5 0.002" />
      </geometry>
      <material name="White" />
    </visual>
    <collision>
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <geometry>
        <box size="1.0 0.5 0.002" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="styrofoam_plate">
    <material>handle/DecimeterGrid</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>false</selfCollide>
  </gazebo>

  <joint name="$styrofoam_fix" type="fixed" >
    <parent link="table_plate" />
    <child link="styrofoam_plate" />
    <origin xyz="0 0 ${table_top_thickness/2+0.001}" rpy="0 0 0" />
  </joint>

</robot>
