<?xml version="1.0"?>
<robot name="table" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- modified table model from simulator_gazebo/gazebo_worlds/objects/table.model
       The experiment tables in lab room F329 are 140x70 cm2 and height 72cm,
       normal tables are 160x80 and height 72cm. Leg diameter is 3cm.
  -->

  <xacro:property name="table_height" value="0.72" />
  <xacro:property name="table_width" value="1.40" />
  <xacro:property name="table_depth" value="0.70" />
  <xacro:property name="leg_radius" value="0.015" />
  <xacro:property name="table_x" value="0.0" />
  <xacro:property name="table_y" value="0.0" />
  <xacro:property name="table_z" value="0.0" />

  <xacro:property name="table_top_thickness" value="0.02"/>

  <link name="table_plate">
    <inertial>
      <mass value="8.0" />
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <inertia ixx="1" ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <geometry>
        <box size="${table_width} ${table_depth} ${table_top_thickness}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${table_height - table_top_thickness/2}" />
      <geometry>
        <box size="${table_width} ${table_depth} ${table_top_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="table_plate">
    <!-- <material>Gazebo/Wood</material>  -->
    <material>handle/KotoWood</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <xacro:macro name="leg" params="name *origin">

    <link name="${name}">
      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 ${table_height/2 - table_top_thickness/2}" />
        <inertia ixx="0.1" ixy="0"  ixz="0" iyy="0.1" iyz="0" izz="0.01" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${table_height/2 - table_top_thickness/2}" />
        <geometry>
          <box size="${2*leg_radius} ${2*leg_radius} ${table_height-table_top_thickness}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${table_height/2-table_top_thickness/2}" />
        <geometry>
          <box size="${2*leg_radius} ${2*leg_radius} ${table_height-table_top_thickness}" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="${name}">
      <material>Gazebo/Grey</material>
      <mu1>1000.0</mu1>
      <mu2>1000.0</mu2>
      <kp>10000000.0</kp>
      <kd>1.0</kd>
      <selfCollide>true</selfCollide>
    </gazebo>

    <joint name="${name}_joint" type="fixed" >
      <parent link="table_plate" />
      <xacro:insert_block name="origin" />
      <child link="${name}" />
    </joint>

  </xacro:macro>

  <xacro:leg name="leg1">
    <origin xyz="${-0.5*table_width+leg_radius} ${-0.5*table_depth+leg_radius} 0" rpy="0 0 0" />
  </xacro:leg>

  <xacro:leg name="leg2">
    <origin xyz="${-0.5*table_width+leg_radius} ${+0.5*table_depth-leg_radius} 0" rpy="0 0 0" />
  </xacro:leg>

  <xacro:leg name="leg3">
    <origin xyz="${+0.5*table_width-leg_radius} ${-0.5*table_depth+leg_radius} 0" rpy="0 0 0" />
  </xacro:leg>

  <xacro:leg name="leg4">
    <origin xyz="${+0.5*table_width-leg_radius} ${+0.5*table_depth-leg_radius} 0" rpy="0 0 0" />
  </xacro:leg>

</robot>
